[package]
name = "aptosforo"
version = "1.0.0"
authors = []

[addresses]
# escalation_manager_addr = "0xe1c93f55211a61e0395c0d3fee3c8fd30ec36cc0ec49bd1d6a727cbb3c1704a8"
# aptosforo_addr          = '0xe1c93f55211a61e0395c0d3fee3c8fd30ec36cc0ec49bd1d6a727cbb3c1704a8'
# treasury_addr           = '0xe1c93f55211a61e0395c0d3fee3c8fd30ec36cc0ec49bd1d6a727cbb3c1704a8'
aptosforo_addr  = '_'
escalation_manager_addr = '_'
treasury_addr           = '_'

[dev-addresses]
aptosforo_addr          = '0x111'
escalation_manager_addr = '0x222'
treasury_addr           = '0x333'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]